export const UPDATE_SEARCHTEXT = 'UPDATE_SEARCHTEXT'
export const TOGGLE_PERCAPITA = 'TOGGLE_PERCAPITA'
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY'
export const INIT_SEARCH_RESULTS = 'INIT_SEARCH_RESULTS'